# Generated by Django 3.2.6 on 2021-11-02 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_name', models.CharField(max_length=100)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExpInOrg', to='accounts.organization')),
            ],
        ),
        migrations.RemoveField(
            model_name='works_as',
            name='position',
        ),
        migrations.RemoveField(
            model_name='works_as',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='position',
        ),
        migrations.AlterField(
            model_name='located_in',
            name='est_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Works_As',
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExpOfUser', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='experience',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AboutExp', to='accounts.experience'),
        ),
    ]
