# Generated by Django 3.2.6 on 2021-11-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211102_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publishedTime',
            new_name='published_time',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
