# Generated by Django 3.2.6 on 2021-11-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0002_auto_20211113_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_attached_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UnderPost', to='PostApp.post'),
        ),
    ]
