# Generated by Django 3.2.6 on 2021-11-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpApp.city')),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PosInPlace', to='ExpApp.district'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
