# Generated by Django 3.2.6 on 2021-11-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpApp', '0002_alter_place_place_id'),
        ('ExpApp', '0002_auto_20211107_2000'),
    ]

    operations = [
    ]
