# Generated by Django 3.2.6 on 2021-11-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpApp', '0003_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
