# Generated by Django 3.2.6 on 2021-11-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpApp', '0004_delete_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
