# Generated by Django 3.2.6 on 2021-11-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpApp', '0005_alter_district_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='city_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ExpApp.city'),
        ),
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('city_id', 'district_id')},
        ),
    ]
