# Generated by Django 3.2.6 on 2021-11-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpApp', '0007_auto_20211116_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
