<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-11-07 08:04
=======
# Generated by Django 3.2.6 on 2021-11-11 11:46
>>>>>>> backend

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=40)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
