# Generated by Django 3.2.6 on 2021-11-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PostApp', '0001_initial'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreatedByUser', to='UserApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Collected_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CollectedInCategory', to='CategoryApp.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostCollectedIn', to='PostApp.post')),
            ],
        ),
    ]
